spring.application.name=music-library-backend
server.port=8080

# MongoDB Configuration (local MongoDB Compass)
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=musiclibrary
#spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.auto-index-creation=true

# JWT Configuration
app.jwt.secret=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
app.jwt.expiration-ms=86400000

# iTunes Search API
itunes.api.base-url=https://itunes.apple.com

# CORS
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000

# Logging
logging.level.com.musiclibrary=DEBUG
logging.level.org.springframework.security=INFO
